### ISSUE TITLE
Module types not resolving correctly. 

### ISSUE THREAD

**Issue by profblackjack** [shimyshack/uid#2]
While looking for solutions to unique element ids in a NuxtJS 3 application, i came across [this blog](https://dev.to/ajscommunications/ssr-friendly-unique-html-ids-in-vue-3-1og9) leading me to this project, which seems to do exactly what I need it to.

However, in version 0.1.7 i'm getting a typescript error for missing declaration file: 
![image](https://user-images.githubusercontent.com/40010790/231856762-bc6857ce-938a-422e-87f6-c715cc804a21.png)

It appears that the `types` field in the package references a non-existing path, and this is the types location that is being picked up.
![image](https://user-images.githubusercontent.com/40010790/231857043-449cab30-0f6c-458d-b496-5f48af95a559.png)

once i change the top level `types` value to match the nested value in `exports['.'].types`, the issue goes away:
![image](https://user-images.githubusercontent.com/40010790/231857306-951390b3-e7c4-461c-835b-b0cdd0df7b7d.png)

**Comment by jshimkoski** [comment]
Thanks for letting me know. Working on a fix.

**Comment by jshimkoski** [comment]
I just released version 0.1.9 with the fix you found in place.

Thanks again.
